### ISSUE TITLE
Entity with externally linked DTD

### ISSUE THREAD

**Issue by Bimbinbiribong** [uli-weltersbach/XPathInformation#14]
If I have entity in my XML file and externally (but correctly) linked DTD explaining meaning of this entity, right click doesnt offer the standard menu.
Note: If I use internal DTD in my XML file, it works with no problem.

**Comment by uli-weltersbach** [comment]
Thanks for reporting this.
Is any error being displayed?
Can you share a simple example which I can work off of?

**Comment by Bimbinbiribong** [comment]
No error shows up.
If I use my correctly defined entity: https://ctrlv.cz/gSUs (XPath options don't pop up)
If I do not use an entity: https://ctrlv.cz/2tdY

Xml: https://pastebin.com/vDjBkPqU
Dtd: https://pastebin.com/UwSA9zxw

Note: I use a fully updated VS 2017.

**Comment by uli-weltersbach** [comment]
I was able to reproduce the issue and hope to have a fix soon.

**Comment by uli-weltersbach** [comment]
@Bimbinbiribong: The issue should be fixed now, but you have to specify the full file path (e.g. "C:\WoW\GameObjDb.dtd") or fully qualified URL ("https://mydomain.com/GameObjDb.dtd") to the DTD file.
The new version of the VS plugin should be out in a couple of hours.

**Comment by Bimbinbiribong** [comment]
Thanks, it's weird not to have relative paths working tho...

**Comment by uli-weltersbach** [comment]
Hmm, you're right, I'll try to work it in there.

**Comment by uli-weltersbach** [comment]
@Bimbinbiribong: I just released v4.2.2 which should support relative paths as well. 
Let me know if it works for you.

**Comment by Bimbinbiribong** [comment]
@uli-weltersbach It seems to be working. :)
