### ISSUE TITLE
usage in vs2017 preview

### ISSUE THREAD

**Issue by SinxHe** [uli-weltersbach/XPathInformation#15]
i found it is always gray in vs2017 preview, am i use it wrong?
![qq 20170629002050](https://user-images.githubusercontent.com/9050899/27648367-e930c4f8-5c60-11e7-8c7f-57beca0c4074.png)

**Comment by uli-weltersbach** [comment]
It will only work if your document is a valid XML document.
What you're looking at is HTML, which might include some invalid syntax from an XML perspective.

**Comment by SinxHe** [comment]
Hope it can support html feature, after all, HTML is special XML i think. Thanks for your contribution anyway.

**Comment by uli-weltersbach** [comment]
XHTML is XML, and is supported by the extension. All other HTML versions allow markup which would be considered invalid XML, e.g. opening tags with no matching closing tag.
So it's not possible.
