### ISSUE TITLE
How do I configure to show an index based xpath in my status bar?

### ISSUE THREAD

**Issue by jbuedel** [uli-weltersbach/XPathInformation#16]
How do I configure my status bar to show an index based xpath?

That is, I see this...
```/Orders/Order/Job/Part/BundleNumber```

... but I want this...
```/Orders[1]/Order[6]/Job[5]/Part[1]/BundleNumber[1]```

Thanks.

**Comment by uli-weltersbach** [comment]
Hi Josh

That's not currently supported. I should be able to implement it without much hassle, so it'll be configurable via the options page. I'll likely have time over the weekend.

**Comment by jbuedel** [comment]
Great! Thanks.

**Comment by uli-weltersbach** [comment]
Hi Josh

This should be implemented now, let me know what you think.

**Comment by jbuedel** [comment]
That's perfect Uli, thanks.

Just in case you're curious my use case is that I was trying to determine if the same part number appeared in multiple orders. Now I can watch for changes in the status bar as I do a normal search through all instances of the part number.

**Comment by uli-weltersbach** [comment]
Glad it's working! Feel free to [write a review](https://marketplace.visualstudio.com/items?itemName=UliWeltersbach.XPathInformation#review-details) if you like ;)

I'm wondering whether the [XPath Workbench](https://github.com/uli-weltersbach/XPathInformation/wiki/Running-XPaths) could help finding duplicates.

**Comment by jbuedel** [comment]
I think it could, yes. If the workbench allowed the absolute path value as a (optional) column that would have worked even better.
