### ISSUE TITLE
Extension disabled itself

### ISSUE THREAD

**Issue by jxosborne** [uli-weltersbach/XPathInformation#3]
Great Extension, Thanks so much!

I have a small issue; not sure what the problem is...I've been working with the same XML file for over a week now; the extension has been awesome.  But today when I opened it I notice the "Copy XPath" option is disabled in the context menu, and the XPath is no longer appearing in the notification area.  The file has not changed at all.

I've tried creating a new XML file and building a small hierarchy and it seemed to work fine.  I then tried copy/pasting the data into the new XML file and to my surprise the add-on was disabled again!

The XML file in question is on TFS under source control; I can confirm that it has not changed in weeks.

Any ideas as to why the extension has mysteriously stopped working?

Thanks!

**Comment by uli-weltersbach** [comment]
Hey, sorry for the (very) late reply! 
I haven't experienced the behavior you've described myself or heard of anyone else having this issue.

I know it's not much help but "turning it on and off" (uninstalling the plugin and then installing it again) is the only suggestion I have :|

**Comment by jxosborne** [comment]
No worries Uli,

I did try all of that...I went for the Nuclear option and re-imaged my
whole machine.  I had a few other problems that were starting to crop up
anyway.

Works great now!

Thanks!
