### ISSUE TITLE
Simple XPath path

### ISSUE THREAD

**Issue by rocts** [uli-weltersbach/XPathInformation#4]
Hi there,

is it possible to copy the simple path such as the below, rather than including all the namespace info etc?  

/OrderMessage/Order/TransportStages/Stage/Name or
/OrderMessage/Order/TransportStages/Stage[1]/Name

I would never need to use XML spy again if this is possible :-)

many thanks

**Comment by uli-weltersbach** [comment]
Hi, that shouldn't be a problem, I'll add it as soon as possible. Thanks for the feedback! :)

**Comment by uli-weltersbach** [comment]
Hi Rocts,

An additional button is now available from the context menu which copies the XPath excluding any XMLNS from both elements and attributes.
If you find this feature helpful please [rate the plugin](https://visualstudiogallery.msdn.microsoft.com/c06c7b10-41c3-4aa9-8707-570eb9d879e6) :)
