### ISSUE TITLE
SSIS Package Support

### ISSUE THREAD

**Issue by dallyhorton** [uli-weltersbach/XPathInformation#5]
Right clicking a SSIS package and selecting View Code displays the package XML. In this mode the XPath extension doesn't work. Saving a .dtsx file with an .xml file extension and opening within Visual Studio works perfectly. So does opening a .dtsConfig file.

**Comment by uli-weltersbach** [comment]
Hi dallyhorton,

The XPathInformation plugin attaches itself to any Visual Studio editor window which identifies it's content as XML.
You could try to follow [this guide](http://blogs.msdn.com/b/zainnab/archive/2010/08/22/using-custom-file-extension-associations-vstipenv0038.aspx) to associate the .dtsx file extension with the XML editor.
I've never worked with SSIS packages so I haven't tried it myself.
