### ISSUE TITLE
Does not install with newer frameworks installed (4.6)

### ISSUE THREAD

**Issue by jaweier-AT-msn-Dot-com** [uli-weltersbach/XPathInformation#6]
Even though 4.5 installed.... Will not install with new frameworks installed. get the message
"Install Error : Microsoft.VisualStudio.ExtensionManager.MissingTargetFrameworkException: The extension 'XPath Information' requires a version of the .NET Framework that is not installed."

**Comment by uli-weltersbach** [comment]
Hi Jawier,
I'll have a look at the problem as soon as possible.
