### ISSUE TITLE
XPath validation / runner

### ISSUE THREAD

**Issue by tig2810** [uli-weltersbach/XPathInformation#8]
Hi,

Been using your plugin for a while :-) but i sometimes veer back to XML Spy when i want to verify an XPath.  

Would you consider adding an option to type in a query, such as //Invoices/Invoice/Parties/Party[@PartyType='Debtor']/Details/VATNumber
and have it jump to the value or similar?

Thanks

**Comment by uli-weltersbach** [comment]
Hi tig, sorry for not getting back to you!

I'd love to provide that option, but at the same time wonder if there aren't already other plugins out there doing this?

If not, do you have any suggestions/requirements as to how this feature should work?
E.g. 
1. I'd like to use the context menu to open up a text box which allows me to type/paste an XPath.
2. Whenever I change the text value, the XPath is run against the current document. The number of matching nodes is displayed as a result counter.

**Comment by tig2810** [comment]
Hi Uli,
I'm prettry sure you are the only person providing an xpath plugin :-)  
I have uploaded a screenshot from another app to show the concept. Let me know what you think?
I was thinking, after typeing the xpath, it would jump to the value or show not found.
Thanks 
![Uploading 2016-11-11_20-12-15.jpg…]()

**Comment by tig2810** [comment]
![2016-11-11_20-12-15](https://cloud.githubusercontent.com/assets/13333006/20228993/f457e3d0-a84b-11e6-8509-ccb7f2da1acc.jpg)

**Comment by uli-weltersbach** [comment]
I'll see if I can come up with something, it's my first time attempting to implement something dialog'ish in a VS extension.
I'll post an update as soon as I have some sort of prototype.

**Comment by uli-weltersbach** [comment]
Hi tig,
I just release v4.0.0 of the extension which includes an XPath runner, so you can simply update the extension via Visual Studio.

The styling of the XPath runner search results doesn't match Visual Studio, but other than that it should be usable (i.e. can evaluate most stuff incl. summation results etc., search results can be clicked to navigate).

Let me know what you think.

**Comment by tig2810** [comment]
Hi Uli,
It's great! Thanks :-)  I will use and let you know if i have any issues or more ideas.  Working perfectly for what i have tried so far. 
Thanks very much.
